<a href="https://colab.research.google.com/github/NarciSource/Aivle--MiniProject-4-1/blob/main/2.%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%A0%84%EC%B2%98%EB%A6%AC_4%EC%B0%A8%EB%AF%B8%ED%94%84_%EC%97%90%EC%9D%B4%EB%B8%94%EB%9F%AC%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 안녕하세요^^
# AIVLE 미니 프로젝트에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

---

# (실습준비) 데이터 불러오기부터

* 17년도부터 21년도 까지의 데이터를 train set, 22년도의 6개월치 데이터를 test set 으로 설정합니다.

In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [2]:
# 학습 데이터 로딩
train_set = pd.read_csv('/content/drive/MyDrive/aivle/mp4/total.csv')
test_set = pd.read_csv('/content/drive/MyDrive/aivle/mp4/test.csv')
train_set.head()

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,2017-01-01,0,31535.2200,1945.4402,566.4588,631.5581,991.9184,1297.1287,1223.1529,1552.9448,...,1157.6661,1107.6781,1282.9235,1029.4360,998.0414,874.5643,1162.1547,1053.0477,964.3940,2025.4819
1,2017-01-01,1,31188.9174,1930.4766,562.1018,625.2151,1030.6281,1307.7381,1183.0956,1491.5827,...,1120.0051,1102.5198,1271.8997,1027.2574,1038.7528,857.9100,1149.7532,1042.7411,919.0115,2062.2422
2,2017-01-01,2,31240.4974,1921.1864,559.3965,658.7463,1058.7082,1311.9591,1186.2600,1537.3732,...,1103.1547,1112.4579,1282.9366,1027.8901,1020.0177,853.3890,1193.4472,1011.2073,889.9325,1960.1236
3,2017-01-01,3,31442.4314,1946.4476,566.7525,649.0804,1057.9119,1324.2638,1202.1250,1521.2732,...,1116.2165,1102.0668,1260.8472,1007.6650,1042.9554,896.0038,1163.0355,1056.6428,891.9177,2060.1872
4,2017-01-01,4,31922.7751,1953.7713,568.8845,623.2087,1063.2557,1342.9146,1209.2680,1556.0675,...,1187.5457,1120.2232,1281.2738,1064.0655,1045.2130,895.8336,1191.7017,1045.3362,874.4984,2038.6212

In [3]:
test_set.head()

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20220101,0,30509.7386,1884.2082,548.6298,635.1617,816.1686,1140.0136,1310.3109,1528.2100,...,1034.3335,1210.2650,1427.1433,1218.2473,1167.4485,823.9020,1032.1651,872.8850,767.0226,1737.1551
1,20220101,1,30759.5067,1918.5330,558.6242,665.6793,822.6910,1159.5614,1293.1350,1542.7586,...,1072.8086,1193.7476,1403.5719,1248.7765,1180.9186,838.5323,998.1091,862.3041,776.7908,1753.0597
2,20220101,2,31048.8787,2068.1943,602.2013,680.8294,819.7141,1164.5819,1331.9311,1537.8207,...,1090.9845,1208.3281,1410.2452,1268.6557,1197.7707,840.6799,1026.5402,882.2846,772.8478,1757.8801
3,20220101,3,31076.1092,1951.7702,568.3016,690.9847,804.2219,1180.7028,1336.8848,1542.4681,...,1104.3879,1224.9349,1414.4162,1275.0993,1207.1428,856.1711,1042.1205,891.6092,785.1560,1747.8953
4,20220101,4,31714.9309,2058.5797,599.4019,708.3313,847.9704,1168.0681,1355.7735,1586.0121,...,1152.1235,1269.6214,1442.1163,1296.6590,1206.5972,875.1503,1052.5656,877.6836,795.0789,1760.4713

---

# 1. 데이터 전처리

#### [실습문제1] 열 추가
* 기존 '기준일ID'열에서 날짜 데이터를 추출하여 새로운 열로 추가 합니다.
    - pd.to_datetime() 함수를 사용해 '기준일ID'열을 datetime 형식으로 변경하겠습니다.
    - year, month, day 열로 기존 데이터 프레임에 연월일 정보를 저장합니다.
    - 데이터 프레임 열에 대해 날짜 정보를 얻을 때에는 **dt.year**, **dt.month**, **dt.day** 속성을 사용합니다.

In [4]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
train_set['기준일ID'] = pd.to_datetime(train_set['기준일ID'].astype(str))
train_set['year'] = train_set['기준일ID'].apply(lambda d: d.year)
train_set['month'] = train_set['기준일ID'].apply(lambda d: d.month)
train_set['day'] = train_set['기준일ID'].apply(lambda d: d.day)
#train_set['weekday'] = train_set['기준일ID'].apply(lambda d: d.weekday())
train_set.head(1)

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,year,month,day
0,2017-01-01,0,31535.22,1945.4402,566.4588,631.5581,991.9184,1297.1287,1223.1529,1552.9448,...,1029.436,998.0414,874.5643,1162.1547,1053.0477,964.394,2025.4819,2017,1,1

In [5]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
test_set['기준일ID'] = pd.to_datetime(test_set['기준일ID'].astype(str))
test_set['year'] = test_set['기준일ID'].apply(lambda d: d.year)
test_set['month'] = test_set['기준일ID'].apply(lambda d: d.month)
test_set['day'] = test_set['기준일ID'].apply(lambda d: d.day)
#test_set['weekday'] = test_set['기준일ID'].apply(lambda d: d.weekday())
test_set.head(0)

Empty DataFrame
Columns: [기준일ID, 시간대구분, 총생활인구수, 남자0세부터9세생활인구수, 남자10세부터14세생활인구수, 남자15세부터19세생활인구수, 남자20세부터24세생활인구수, 남자25세부터29세생활인구수, 남자30세부터34세생활인구수, 남자35세부터39세생활인구수, 남자40세부터44세생활인구수, 남자45세부터49세생활인구수, 남자50세부터54세생활인구수, 남자55세부터59세생활인구수, 남자60세부터64세생활인구수, 남자65세부터69세생활인구수, 남자70세이상생활인구수, 여자0세부터9세생활인구수, 여자10세부터14세생활인구수, 여자15세부터19세생활인구수, 여자20세부터24세생활인구수, 여자25세부터29세생활인구수, 여자30세부터34세생활인구수, 여자35세부터39세생활인구수, 여자40세부터44세생활인구수, 여자45세부터49세생활인구수, 여자50세부터54세생활인구수, 여자55세부터59세생활인구수, 여자60세부터64세생활인구수, 여자65세부터69세생활인구수, 여자70세이상생활인구수, year, month, day]
Index: []

[0 rows x 34 columns]

In [6]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
man_columns = [column for column in train_set.columns if '남자' in column]
woman_columns = [column for column in train_set.columns if '여자' in column]

train_set['남녀성비'] = train_set[man_columns].sum(axis=1)/train_set[woman_columns].sum(axis=1)
test_set['남녀성비'] = test_set[man_columns].sum(axis=1)/test_set[woman_columns].sum(axis=1)
train_set[:1]

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,year,month,day,남녀성비
0,2017-01-01,0,31535.22,1945.4402,566.4588,631.5581,991.9184,1297.1287,1223.1529,1552.9448,...,998.0414,874.5643,1162.1547,1053.0477,964.394,2025.4819,2017,1,1,0.965969

#### [실습문제2] 불필요한 열 제거 및 열 이름 변경
* df_total과 df_test에서 '총생활인구수'외에 불필요한 열을 제거 하도록 하겠습니다.
* 시간 데이터를 남기고, '시간대구분' column 을 'hour'로 rename 하도록 하겠습니다.

In [7]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
drop_cols = list(filter(lambda s: '세부터' in s or "이상" in s, test_set.columns))
train_set.drop(drop_cols, axis=1, inplace=True)
test_set.drop(drop_cols, axis=1, inplace=True)

In [8]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
train_set.rename(columns={"시간대구분": "hour"}, inplace=True)
test_set.rename(columns={"시간대구분": "hour"}, inplace=True)

In [9]:
train_set.head(0)

Empty DataFrame
Columns: [기준일ID, hour, 총생활인구수, year, month, day, 남녀성비]
Index: []

In [10]:
train_set = train_set.groupby(['month', 'day', 'hour']).mean().reset_index().drop(['year'], axis=1)
train_set.head()

   month  day  hour               기준일ID       총생활인구수      남녀성비
0      1    1     0 2019-01-01 04:48:00  32175.96948  1.002889
1      1    1     1 2019-01-01 04:48:00  32337.59844  1.009861
2      1    1     2 2019-01-01 04:48:00  32610.08464  1.012752
3      1    1     3 2019-01-01 04:48:00  32808.12756  1.010131
4      1    1     4 2019-01-01 04:48:00  33422.36668  1.007293

In [11]:
test_set = test_set.groupby(['month','day', 'hour']).mean().reset_index().drop(['year'], axis=1)
test_set.head()

   month  day  hour      기준일ID      총생활인구수      남녀성비
0      1    1     0 2022-01-01  30509.7386  1.048191
1      1    1     1 2022-01-01  30759.5067  1.039602
2      1    1     2 2022-01-01  31048.8787  1.054242
3      1    1     3 2022-01-01  31076.1092  1.038614
4      1    1     4 2022-01-01  31714.9309  1.060294

#### [실습문제3] 시프트 & 롤링
* shift()를 활용하여 이동할 행 수를 지정합니다.
* rolling()을 활용하여 추가할 이동평균 수를 지정합니다.

In [12]:
target = "총생활인구수"

* 라그 변수 (shift)

In [13]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
train_set["총생활인구수_1시간전"] = train_set["총생활인구수"].shift(-1)
train_set["총생활인구수_3시간전"] = train_set["총생활인구수"].shift(-3)
train_set["총생활인구수_24시간전"] = train_set["총생활인구수"].shift(-24)
display(train_set)
test_set["총생활인구수_1시간전"] = test_set["총생활인구수"].shift(-1)
test_set["총생활인구수_3시간전"] = test_set["총생활인구수"].shift(-3)
test_set["총생활인구수_24시간전"] = test_set["총생활인구수"].shift(-24)

,month,day,hour,기준일ID,총생활인구수,남녀성비,총생활인구수_1시간전,총생활인구수_3시간전,총생활인구수_24시간전
0,1,1,0,2019-01-01 04:48:00,32175.96948,1.002889,32337.59844,32808.12756,32913.09214
1,1,1,1,2019-01-01 04:48:00,32337.59844,1.009861,32610.08464,33422.36668,33097.10618
2,1,1,2,2019-01-01 04:48:00,32610.08464,1.012752,32808.12756,34729.04210,33192.00904
3,1,1,3,2019-01-01 04:48:00,32808.12756,1.010131,33422.36668,35340.74252,33287.21950
4,1,1,4,2019-01-01 04:48:00,33422.36668,1.007293,34729.04210,35088.79430,33831.70980
...,...,...,...,...,...,...,...,...,...
8779,12,31,19,2019-12-31 09:36:00,34600.40446,1.019421,33651.42116,32520.53026,NaN
8780,12,31,20,2019-12-31 09:36:00,33651.42116,1.032702,32940.37470,31783.23902,NaN
8781,12,31,21,2019-12-31 09:36:00,32940.37470,1.032647,32520.53026,NaN,NaN
8782,12,31,22,2019-12-31 09:36:00,32520.53026,1.037571,31783.23902,NaN,NaN
8783,12,31,23,2019-12-31 09:36:00,31783.23902,1.027660,NaN,NaN,NaN

* 이동 평균 (rolling)

In [14]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

train_set['총생활인구수_3시간전평균'] = train_set["총생활인구수"].shift(1).rolling(3, min_periods=1).mean()
train_set['총생활인구수_6시간전평균'] = train_set["총생활인구수"].shift(1).rolling(6, min_periods=1).mean()
train_set['총생활인구수_12시간전평균'] = train_set["총생활인구수"].shift(1).rolling(12, min_periods=1).mean()
train_set['총생활인구수_24시간전평균'] = train_set["총생활인구수"].shift(1).rolling(24, min_periods=1).mean()
display(train_set)
test_set['총생활인구수_3시간전평균'] = test_set["총생활인구수"].shift(1).rolling(3, min_periods=1).mean()
test_set['총생활인구수_6시간전평균'] = test_set["총생활인구수"].shift(1).rolling(6, min_periods=1).mean()
test_set['총생활인구수_12시간전평균'] = test_set["총생활인구수"].shift(1).rolling(12, min_periods=1).mean()
test_set['총생활인구수_24시간전평균'] = test_set["총생활인구수"].shift(1).rolling(24, min_periods=1).mean()

,month,day,hour,기준일ID,총생활인구수,남녀성비,총생활인구수_1시간전,총생활인구수_3시간전,총생활인구수_24시간전,총생활인구수_3시간전평균,총생활인구수_6시간전평균,총생활인구수_12시간전평균,총생활인구수_24시간전평균
0,1,1,0,2019-01-01 04:48:00,32175.96948,1.002889,32337.59844,32808.12756,32913.09214,NaN,NaN,NaN,NaN
1,1,1,1,2019-01-01 04:48:00,32337.59844,1.009861,32610.08464,33422.36668,33097.10618,32175.969480,32175.969480,32175.969480,32175.969480
2,1,1,2,2019-01-01 04:48:00,32610.08464,1.012752,32808.12756,34729.04210,33192.00904,32256.783960,32256.783960,32256.783960,32256.783960
3,1,1,3,2019-01-01 04:48:00,32808.12756,1.010131,33422.36668,35340.74252,33287.21950,32374.550853,32374.550853,32374.550853,32374.550853
4,1,1,4,2019-01-01 04:48:00,33422.36668,1.007293,34729.04210,35088.79430,33831.70980,32585.270213,32482.945030,32482.945030,32482.945030
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,12,31,19,2019-12-31 09:36:00,34600.40446,1.019421,33651.42116,32520.53026,NaN,36552.906647,37350.387910,37784.769185,36031.388413
8780,12,31,20,2019-12-31 09:36:00,33651.42116,1.032702,32940.37470,31783.23902,NaN,35961.475807,36641.259283,37487.481890,36016.215257
8781,12,31,21,2019-12-31 09:36:00,32940.37470,1.032647,32520.53026,NaN,NaN,34805.265360,35828.463307,37093.309530,36006.878525
8782,12,31,22,2019-12-31 09:36:00,32520.53026,1.037571,31783.23902,NaN,NaN,33730.733440,35141.820043,36652.939637,35980.770792
8783,12,31,23,2019-12-31 09:36:00,31783.23902,1.027660,NaN,NaN,NaN,33037.442040,34499.458923,36151.359210,35933.305498

#### [실습문제4] 결측치 처리 및 불필요한 열 제거
* 불필요한 열을 추가로 제거 하겠습니다.(시간 관련 행들)
* 롤링 & 시프트 과정에서 발생한 결측치를 처리하도록 하겠습니다.

In [15]:
train_set.drop('기준일ID', axis=1, inplace=True)
test_set.drop('기준일ID', axis=1, inplace=True)

train_set.dropna(axis=0, inplace=True)
test_set.dropna(axis=0, inplace=True)

#### [실습문제5] train, test 데이터 나누기
* df_total과 df_test를 각각 train_x, train_y, test_x, test_y 로 나누어 주세요.
* 인덱스를 리셋 해주세요.

In [16]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

train_x, train_y = train_set.drop(target, axis=1), train_set[target]
test_x, test_y = test_set.drop(target, axis=1), test_set[target]

In [17]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
display(train_x)
display(test_x)

,month,day,hour,남녀성비,총생활인구수_1시간전,총생활인구수_3시간전,총생활인구수_24시간전,총생활인구수_3시간전평균,총생활인구수_6시간전평균,총생활인구수_12시간전평균,총생활인구수_24시간전평균
1,1,1,1,1.009861,32610.08464,33422.36668,33097.10618,32175.969480,32175.969480,32175.969480,32175.969480
2,1,1,2,1.012752,32808.12756,34729.04210,33192.00904,32256.783960,32256.783960,32256.783960,32256.783960
3,1,1,3,1.010131,33422.36668,35340.74252,33287.21950,32374.550853,32374.550853,32374.550853,32374.550853
4,1,1,4,1.007293,34729.04210,35088.79430,33831.70980,32585.270213,32482.945030,32482.945030,32482.945030
5,1,1,5,1.009817,35340.74252,35493.12720,35696.80930,32946.859627,32670.829360,32670.829360,32670.829360
...,...,...,...,...,...,...,...,...,...,...,...
8755,12,30,19,1.030794,33875.50272,33659.69732,34600.40446,36466.630427,37289.699990,37691.741460,36049.404496
8756,12,30,20,1.042064,33566.96028,33340.52984,33651.42116,35916.985587,36668.710070,37432.989885,36049.028488
8757,12,30,21,1.049342,33659.69732,33186.14146,32940.37470,34928.909393,35928.336740,37083.810487,36037.856698
8758,12,30,22,1.043915,33340.52984,33456.79882,32520.53026,34135.674407,35301.152417,36699.933897,36029.155512
8759,12,30,23,1.047435,33186.14146,33610.76722,31783.23902,33700.720107,34808.852847,36311.176433,36042.788489

,month,day,hour,남녀성비,총생활인구수_1시간전,총생활인구수_3시간전,총생활인구수_24시간전,총생활인구수_3시간전평균,총생활인구수_6시간전평균,총생활인구수_12시간전평균,총생활인구수_24시간전평균
1,1,1,1,1.039602,31048.8787,31714.9309,31024.0247,30509.738600,30509.738600,30509.738600,30509.738600
2,1,1,2,1.054242,31076.1092,33368.3456,31195.0739,30634.622650,30634.622650,30634.622650,30634.622650
3,1,1,3,1.038614,31714.9309,34962.7828,31349.9642,30772.708000,30772.708000,30772.708000,30772.708000
4,1,1,4,1.060294,33368.3456,34948.9644,31993.0440,30961.498200,30848.558300,30848.558300,30848.558300
5,1,1,5,1.076913,34962.7828,34311.2156,33046.6075,31279.972933,31021.832820,31021.832820,31021.832820
...,...,...,...,...,...,...,...,...,...,...,...
4315,6,29,19,1.035272,30425.9054,30232.2846,32969.6040,34402.456500,36157.912267,37199.470008,34778.673200
4316,6,29,20,1.048203,30352.8869,31251.4119,31014.6597,33147.015133,35012.639267,36730.955450,34727.917996
4317,6,29,21,1.046618,30232.2846,31768.1506,30923.2923,31698.686500,33728.969267,36027.910958,34734.121325
4318,6,29,22,1.072724,31251.4119,31642.9209,30509.5463,30822.871167,32612.663833,35359.087775,34723.521104
4319,6,29,23,1.056849,31768.1506,32038.0910,31184.8763,30337.025633,31742.020383,34674.893717,34704.718083

## 다음 단계를 위해서 데이터를 저장하겠습니다.

In [18]:
# CSV로 저장
train_x.to_csv('/content/drive/MyDrive/aivle/mp4/train_x.csv', index = False)
train_y.to_csv('/content/drive/MyDrive/aivle/mp4/train_y.csv', index = False)
test_x.to_csv('/content/drive/MyDrive/aivle/mp4/test_x.csv', index = False)
test_y.to_csv('/content/drive/MyDrive/aivle/mp4/test_y.csv', index = False)

---